### ISSUE TITLE
Error when linking files

### ISSUE THREAD

**Issue by bibilujan** [oicr-gsi/data_release#55]
Working on a data release ticket and got a "list index out of range" error, and the files are not linked: 
`$ dare link -w bcl2fastq -s fastqs -l samples.txt -pr GBMDAS
Extracted files from File Provenance Report
Traceback (most recent call last):
  File "/.mounts/labs/gsi/modulator/sw/Ubuntu20.04/dare-1.0.0/bin/../share/dare.py", line 3905, in <module>
    args.func(args)
  File "/.mounts/labs/gsi/modulator/sw/Ubuntu20.04/dare-1.0.0/bin/../share/dare.py", line 723, in link_files
    write_md5sum(files, outputfile)
  File "/.mounts/labs/gsi/modulator/sw/Ubuntu20.04/dare-1.0.0/bin/../share/dare.py", line 625, in write_md5sum
    if 'md5' in data[list(data.keys())[0]]:
IndexError: list index out of range
`
I have linked the data manually and released the files. 
Ticket: https://jira.oicr.on.ca/browse/GDR-1125

**Comment by bibilujan** [comment]
This issue occurred because the data release ticket lists the libraries as:
GBMDAS_0008_02_LB02
GBMDAS_0017_01_LB03
GBMDAS_0008_02_LB02
GBMDAS_0017_01_LB03
These are missing the last two digits. No issue with dare.
